/* ============================================================================
   data.js
   ----------------------------------------------------------------------------
   The "database" for this project. Since the app has no backend, our entire
   catalog lives here as a plain JavaScript array of objects. Each item has a
   consistent shape so the recommendation engine (in script.js) can treat
   movies, books, and products identically — it only ever looks at `genres`.
   ============================================================================ */

const ITEMS = [
  // ---------------------------------------------------------------- MOVIES
  {
    id: 1,
    title: "Inception",
    category: "Movie",
    genres: ["Sci-Fi", "Action", "Thriller", "Mind-Bending"],
    description: "A skilled thief who infiltrates dreams is offered a chance to have his past erased if he can plant an idea deep in a target's subconscious.",
    rating: 8.8,
    image: "https://picsum.photos/seed/inception/400/300",
  },
  {
    id: 2,
    title: "The Matrix",
    category: "Movie",
    genres: ["Sci-Fi", "Action", "Mind-Bending", "Cyberpunk"],
    description: "A computer programmer discovers reality as he knows it is a simulation, and joins a rebellion against its controllers.",
    rating: 8.7,
    image: "https://picsum.photos/seed/matrix/400/300",
  },
  {
    id: 3,
    title: "Interstellar",
    category: "Movie",
    genres: ["Sci-Fi", "Drama", "Space", "Emotional"],
    description: "A team of explorers travels through a wormhole in search of a new home for humanity as Earth becomes uninhabitable.",
    rating: 8.6,
    image: "https://picsum.photos/seed/interstellar/400/300",
  },
  {
    id: 4,
    title: "The Dark Knight",
    category: "Movie",
    genres: ["Action", "Crime", "Thriller", "Superhero"],
    description: "Batman faces his greatest psychological and physical test when a criminal mastermind known as the Joker wreaks havoc on Gotham.",
    rating: 9.0,
    image: "https://picsum.photos/seed/darkknight/400/300",
  },
  {
    id: 5,
    title: "Parasite",
    category: "Movie",
    genres: ["Drama", "Thriller", "Social Commentary"],
    description: "A poor family schemes to become employed by a wealthy household, leading to unexpected and dramatic consequences.",
    rating: 8.6,
    image: "https://picsum.photos/seed/parasite/400/300",
  },
  {
    id: 6,
    title: "La La Land",
    category: "Movie",
    genres: ["Romance", "Musical", "Drama", "Emotional"],
    description: "A jazz pianist and an aspiring actress fall in love while pursuing their dreams in Los Angeles.",
    rating: 8.0,
    image: "https://picsum.photos/seed/lalaland/400/300",
  },
  {
    id: 7,
    title: "Get Out",
    category: "Movie",
    genres: ["Horror", "Thriller", "Social Commentary", "Mystery"],
    description: "A young man uncovers a disturbing secret when he visits his girlfriend's family estate for the first time.",
    rating: 7.7,
    image: "https://picsum.photos/seed/getout/400/300",
  },
  {
    id: 8,
    title: "Spirited Away",
    category: "Movie",
    genres: ["Animation", "Fantasy", "Adventure", "Emotional"],
    description: "A young girl wanders into a spirit world and must find the courage to free herself and her parents from it.",
    rating: 8.6,
    image: "https://picsum.photos/seed/spiritedaway/400/300",
  },
  {
    id: 9,
    title: "Whiplash",
    category: "Movie",
    genres: ["Drama", "Music", "Emotional"],
    description: "A young drummer enrolls at a competitive music school and is pushed to his limits by an abusive instructor.",
    rating: 8.5,
    image: "https://picsum.photos/seed/whiplash/400/300",
  },
  {
    id: 10,
    title: "Mad Max: Fury Road",
    category: "Movie",
    genres: ["Action", "Adventure", "Post-Apocalyptic"],
    description: "In a desert wasteland, a woman rebels against a tyrannical ruler in search of her homeland with the aid of a group of female prisoners.",
    rating: 8.1,
    image: "https://picsum.photos/seed/madmax/400/300",
  },

  // ------------------------------------------------------------------ BOOKS
  {
    id: 11,
    title: "Dune",
    category: "Book",
    genres: ["Sci-Fi", "Adventure", "Space", "Politics"],
    description: "A young noble becomes entangled in a struggle for control of a desert planet that holds the key to the universe's most valuable resource.",
    rating: 8.9,
    image: "https://picsum.photos/seed/dune/400/300",
  },
  {
    id: 12,
    title: "1984",
    category: "Book",
    genres: ["Dystopian", "Politics", "Sci-Fi", "Social Commentary"],
    description: "A man living under a totalitarian regime begins to question the Party's control over truth, thought, and history.",
    rating: 8.8,
    image: "https://picsum.photos/seed/1984/400/300",
  },
  {
    id: 13,
    title: "The Hobbit",
    category: "Book",
    genres: ["Fantasy", "Adventure", "Mythology"],
    description: "A reluctant hobbit joins a company of dwarves on a quest to reclaim their mountain home from a fearsome dragon.",
    rating: 8.5,
    image: "https://picsum.photos/seed/hobbit/400/300",
  },
  {
    id: 14,
    title: "The Silent Patient",
    category: "Book",
    genres: ["Thriller", "Mystery", "Psychological"],
    description: "A woman's refusal to speak after a violent act draws a psychotherapist into a search for the truth behind her silence.",
    rating: 8.2,
    image: "https://picsum.photos/seed/silentpatient/400/300",
  },
  {
    id: 15,
    title: "Sapiens",
    category: "Book",
    genres: ["Non-Fiction", "History", "Science"],
    description: "A sweeping look at how Homo sapiens came to dominate the planet through shared myths, cooperation, and revolutions in thought.",
    rating: 8.4,
    image: "https://picsum.photos/seed/sapiens/400/300",
  },
  {
    id: 16,
    title: "The Fault in Our Stars",
    category: "Book",
    genres: ["Romance", "Drama", "Emotional", "Young Adult"],
    description: "Two teenagers with cancer meet at a support group and fall in love while confronting mortality together.",
    rating: 7.9,
    image: "https://picsum.photos/seed/faultstars/400/300",
  },
  {
    id: 17,
    title: "Atomic Habits",
    category: "Book",
    genres: ["Non-Fiction", "Self-Help", "Productivity"],
    description: "A practical guide to building good habits and breaking bad ones through small, incremental changes.",
    rating: 8.3,
    image: "https://picsum.photos/seed/atomichabits/400/300",
  },
  {
    id: 18,
    title: "The Martian",
    category: "Book",
    genres: ["Sci-Fi", "Adventure", "Space", "Survival"],
    description: "An astronaut stranded on Mars must use ingenuity and science to survive until a rescue mission can reach him.",
    rating: 8.4,
    image: "https://picsum.photos/seed/martian/400/300",
  },
  {
    id: 19,
    title: "Gone Girl",
    category: "Book",
    genres: ["Thriller", "Mystery", "Psychological"],
    description: "A man becomes the prime suspect in his wife's disappearance as dark secrets about their marriage come to light.",
    rating: 8.1,
    image: "https://picsum.photos/seed/gonegirl/400/300",
  },
  {
    id: 20,
    title: "Educated",
    category: "Book",
    genres: ["Non-Fiction", "Memoir", "Emotional"],
    description: "A woman raised in a strict, isolated household fights to educate herself and reconcile with the family she leaves behind.",
    rating: 8.5,
    image: "https://picsum.photos/seed/educated/400/300",
  },

  // -------------------------------------------------------------- PRODUCTS
  {
    id: 21,
    title: "AeroFit Wireless Earbuds",
    category: "Product",
    genres: ["Audio", "Wireless", "Fitness", "Compact"],
    description: "Sweat-resistant wireless earbuds with noise isolation, built for workouts and daily commutes.",
    rating: 4.5,
    image: "https://picsum.photos/seed/earbuds/400/300",
  },
  {
    id: 22,
    title: "TrailBlaze Running Shoes",
    category: "Product",
    genres: ["Fitness", "Footwear", "Outdoor"],
    description: "Lightweight running shoes with responsive cushioning designed for long-distance comfort on any terrain.",
    rating: 4.6,
    image: "https://picsum.photos/seed/shoes/400/300",
  },
  {
    id: 23,
    title: "PulseBand Smartwatch",
    category: "Product",
    genres: ["Wearable", "Fitness", "Wireless", "Tech"],
    description: "A smartwatch that tracks heart rate, sleep, and workouts, with seamless smartphone notifications.",
    rating: 4.4,
    image: "https://picsum.photos/seed/smartwatch/400/300",
  },
  {
    id: 24,
    title: "NimbusCloud Mechanical Keyboard",
    category: "Product",
    genres: ["Tech", "Productivity", "Compact"],
    description: "A tactile mechanical keyboard with hot-swappable switches, designed for both gaming and productivity.",
    rating: 4.7,
    image: "https://picsum.photos/seed/keyboard/400/300",
  },
  {
    id: 25,
    title: "QuietSpace Noise-Cancelling Headphones",
    category: "Product",
    genres: ["Audio", "Wireless", "Travel"],
    description: "Over-ear headphones with adaptive noise cancellation, ideal for focused work and long flights.",
    rating: 4.6,
    image: "https://picsum.photos/seed/headphones/400/300",
  },
  {
    id: 26,
    title: "SunPeak Camping Tent",
    category: "Product",
    genres: ["Outdoor", "Travel", "Adventure"],
    description: "A lightweight, weatherproof two-person tent that sets up in under five minutes.",
    rating: 4.5,
    image: "https://picsum.photos/seed/tent/400/300",
  },
  {
    id: 27,
    title: "BrewMaster Pour-Over Coffee Set",
    category: "Product",
    genres: ["Home", "Lifestyle", "Compact"],
    description: "A minimalist glass pour-over set for brewing café-quality coffee at home.",
    rating: 4.3,
    image: "https://picsum.photos/seed/coffee/400/300",
  },
  {
    id: 28,
    title: "FlexCore Yoga Mat",
    category: "Product",
    genres: ["Fitness", "Home", "Lifestyle"],
    description: "A non-slip, extra-thick yoga mat designed for comfort during floor exercises and stretching.",
    rating: 4.5,
    image: "https://picsum.photos/seed/yogamat/400/300",
  },
  {
    id: 29,
    title: "VoyagePack Travel Backpack",
    category: "Product",
    genres: ["Travel", "Outdoor", "Productivity"],
    description: "A carry-on-friendly backpack with a padded laptop sleeve and expandable storage for trips of any length.",
    rating: 4.6,
    image: "https://picsum.photos/seed/backpack/400/300",
  },
  {
    id: 30,
    title: "GlowDesk LED Desk Lamp",
    category: "Product",
    genres: ["Home", "Productivity", "Tech"],
    description: "An adjustable LED desk lamp with multiple brightness levels and a built-in wireless charging pad.",
    rating: 4.4,
    image: "https://picsum.photos/seed/desklamp/400/300",
  },

  // ------------------------------------------------------------- BONUS SET
  {
    id: 31,
    title: "Blade Runner 2049",
    category: "Movie",
    genres: ["Sci-Fi", "Mystery", "Cyberpunk", "Mind-Bending"],
    description: "A young blade runner unearths a long-buried secret that leads him to track down a former blade runner missing for decades.",
    rating: 8.0,
    image: "https://picsum.photos/seed/bladerunner/400/300",
  },
  {
    id: 32,
    title: "Project Hail Mary",
    category: "Book",
    genres: ["Sci-Fi", "Space", "Adventure", "Survival"],
    description: "A lone astronaut wakes up with no memory on a solo mission that may determine the fate of humanity.",
    rating: 8.7,
    image: "https://picsum.photos/seed/hailmary/400/300",
  },
  {
    id: 33,
    title: "CoreFlow Resistance Bands Set",
    category: "Product",
    genres: ["Fitness", "Home", "Compact"],
    description: "A set of five resistance bands for full-body strength training, suitable for home or travel workouts.",
    rating: 4.4,
    image: "https://picsum.photos/seed/bands/400/300",
  },
];
